config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-connectors:
      branch: master
      repo: https://github.com/ARGOeu/argo-connectors.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-connectors git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-peach-schnauzer.sh
        container: qc.acc_boozy-scarlet-urchin
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-connectors find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-maroon-bloodhound.sh
        container: qc.doc_skimpy-cinnabar-uakari
      github.com/ARGOeu/argo-connectors git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-wisteria-cat.sh
        container: qc.doc_sleepy-chestnut-tang
      github.com/ARGOeu/argo-connectors markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-ochre-catfish.sh
        container: qc.doc_hazy-goldenrod-hyena
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-connectors licensee:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-lilac-panda.sh
        container: qc.lic_bumpy-myrtle-hedgehog
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-connectors bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-lemon-seahorse.sh
        container: qc.sec_sunny-buff-pinscher
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-connectors flake8:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-eggplant-sloth.sh
        container: qc.sty_squeaky-rose-vulture
      github.com/ARGOeu/argo-connectors hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-ecru-turkey.sh
        container: qc.sty_squirrely-flax-lynx
      github.com/ARGOeu/argo-connectors jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-gamboge-orangutan.sh
        container: qc.sty_skimpy-lime-rottweiler
  QC.Uni:
    repos:
      github.com/ARGOeu/argo-connectors pytest:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-tomato-catfish.sh
        container: qc.uni_wiggy-persimmon-impala
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-connectors get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-blue-toad.sh
        container: qc.ver_stealthy-chocolate-chicken
timeout: 5400
